image: 
  name: node:10
  memory: 8192

pipelines:
  branches:
    test:
      - step:
          name: Build
          script:
            - npm install
            - npm install -g @angular/cli@8.3.20
            - ng build hybrid-app -c=test --prod
          artifacts:
            - dist/**
      - step:
          name: Deployment
          script:
            - pipe: atlassian/aws-s3-deploy:0.3.7
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID_TEST
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_TEST
                AWS_DEFAULT_REGION: "eu-west-1"
                S3_BUCKET: 'undp-jtf-ceici-test-web'
                LOCAL_PATH: dist/apps/hybrid-app/
      - step:
          name: Invalidations
          script:
            - pipe: atlassian/aws-cloudfront-invalidate:0.4.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID_TEST # Optional if already defined in the context.
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_TEST # Optional if already defined in the context.
                AWS_DEFAULT_REGION: "eu-west-1" # Optional if already defined in the context.
                DISTRIBUTION_ID: "EIVKLLVUC0LMW"
                PATHS: "/*"

