version: '3'

services:
  eview-clients:
    container_name: eview-clients
    build: .
    image: eview-clients
    ports:
      - 4200:4200
      # - 4201:4201
    volumes:
      - .:/workspace
    command: >
      bash -c "
        npm install &&
        npm rebuild node-sass &&
        ng serve hybrid-app --port 4200 --host=0.0.0.0 --no-open
        # ng serve web-app --port 4200 --host=0.0.0.0 --no-open &
        # ng serve mobile-app --port 4201 --host=0.0.0.0 --no-open
      "
